//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EconoFood.Admin.PedidoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pedido", Namespace="http://schemas.datacontract.org/2004/07/EconoFood.Services.DTO")]
    [System.SerializableAttribute()]
    public partial class Pedido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataRecebimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoReceptorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdEntregadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeEntregadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceptorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<EconoFood.Admin.PedidoService.ePedidoStatusPagamento> StatusPagamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<EconoFood.Admin.PedidoService.ePedidoStatusPedido> StatusPedidoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataPedido {
            get {
                return this.DataPedidoField;
            }
            set {
                if ((this.DataPedidoField.Equals(value) != true)) {
                    this.DataPedidoField = value;
                    this.RaisePropertyChanged("DataPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataRecebimento {
            get {
                return this.DataRecebimentoField;
            }
            set {
                if ((this.DataRecebimentoField.Equals(value) != true)) {
                    this.DataRecebimentoField = value;
                    this.RaisePropertyChanged("DataRecebimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentoReceptor {
            get {
                return this.DocumentoReceptorField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoReceptorField, value) != true)) {
                    this.DocumentoReceptorField = value;
                    this.RaisePropertyChanged("DocumentoReceptor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((this.IdClienteField.Equals(value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short IdEntregador {
            get {
                return this.IdEntregadorField;
            }
            set {
                if ((this.IdEntregadorField.Equals(value) != true)) {
                    this.IdEntregadorField = value;
                    this.RaisePropertyChanged("IdEntregador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPedido {
            get {
                return this.IdPedidoField;
            }
            set {
                if ((this.IdPedidoField.Equals(value) != true)) {
                    this.IdPedidoField = value;
                    this.RaisePropertyChanged("IdPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeCliente {
            get {
                return this.NomeClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeClienteField, value) != true)) {
                    this.NomeClienteField = value;
                    this.RaisePropertyChanged("NomeCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeEntregador {
            get {
                return this.NomeEntregadorField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeEntregadorField, value) != true)) {
                    this.NomeEntregadorField = value;
                    this.RaisePropertyChanged("NomeEntregador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Receptor {
            get {
                return this.ReceptorField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceptorField, value) != true)) {
                    this.ReceptorField = value;
                    this.RaisePropertyChanged("Receptor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<EconoFood.Admin.PedidoService.ePedidoStatusPagamento> StatusPagamento {
            get {
                return this.StatusPagamentoField;
            }
            set {
                if ((this.StatusPagamentoField.Equals(value) != true)) {
                    this.StatusPagamentoField = value;
                    this.RaisePropertyChanged("StatusPagamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<EconoFood.Admin.PedidoService.ePedidoStatusPedido> StatusPedido {
            get {
                return this.StatusPedidoField;
            }
            set {
                if ((this.StatusPedidoField.Equals(value) != true)) {
                    this.StatusPedidoField = value;
                    this.RaisePropertyChanged("StatusPedido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ePedido.StatusPagamento", Namespace="http://schemas.datacontract.org/2004/07/EconoFood.Services.DTO.Enum")]
    public enum ePedidoStatusPagamento : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pendente = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pago = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Estornado = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ePedido.StatusPedido", Namespace="http://schemas.datacontract.org/2004/07/EconoFood.Services.DTO.Enum")]
    public enum ePedidoStatusPedido : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PedidoRealizado = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AguardandoPagamento = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmissaoNotaFiscal = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProdutoEmTransporte = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProdutoEntregue = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cancelado = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PedidoService.IPedido")]
    public interface IPedido {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedido/Listar", ReplyAction="http://tempuri.org/IPedido/ListarResponse")]
        System.Collections.Generic.List<EconoFood.Admin.PedidoService.Pedido> Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedido/Listar", ReplyAction="http://tempuri.org/IPedido/ListarResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<EconoFood.Admin.PedidoService.Pedido>> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedido/Pesquisar", ReplyAction="http://tempuri.org/IPedido/PesquisarResponse")]
        System.Collections.Generic.List<EconoFood.Admin.PedidoService.Pedido> Pesquisar(EconoFood.Admin.PedidoService.Pedido pedido, System.DateTime inicio, System.DateTime fim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedido/Pesquisar", ReplyAction="http://tempuri.org/IPedido/PesquisarResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<EconoFood.Admin.PedidoService.Pedido>> PesquisarAsync(EconoFood.Admin.PedidoService.Pedido pedido, System.DateTime inicio, System.DateTime fim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedido/Gravar", ReplyAction="http://tempuri.org/IPedido/GravarResponse")]
        int Gravar(EconoFood.Admin.PedidoService.Pedido pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedido/Gravar", ReplyAction="http://tempuri.org/IPedido/GravarResponse")]
        System.Threading.Tasks.Task<int> GravarAsync(EconoFood.Admin.PedidoService.Pedido pedido);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPedidoChannel : EconoFood.Admin.PedidoService.IPedido, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PedidoClient : System.ServiceModel.ClientBase<EconoFood.Admin.PedidoService.IPedido>, EconoFood.Admin.PedidoService.IPedido {
        
        public PedidoClient() {
        }
        
        public PedidoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PedidoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<EconoFood.Admin.PedidoService.Pedido> Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<EconoFood.Admin.PedidoService.Pedido>> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public System.Collections.Generic.List<EconoFood.Admin.PedidoService.Pedido> Pesquisar(EconoFood.Admin.PedidoService.Pedido pedido, System.DateTime inicio, System.DateTime fim) {
            return base.Channel.Pesquisar(pedido, inicio, fim);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<EconoFood.Admin.PedidoService.Pedido>> PesquisarAsync(EconoFood.Admin.PedidoService.Pedido pedido, System.DateTime inicio, System.DateTime fim) {
            return base.Channel.PesquisarAsync(pedido, inicio, fim);
        }
        
        public int Gravar(EconoFood.Admin.PedidoService.Pedido pedido) {
            return base.Channel.Gravar(pedido);
        }
        
        public System.Threading.Tasks.Task<int> GravarAsync(EconoFood.Admin.PedidoService.Pedido pedido) {
            return base.Channel.GravarAsync(pedido);
        }
    }
}
