//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EconoFood.ProdutoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produto", Namespace="http://schemas.datacontract.org/2004/07/EconoFood.Services.DTO")]
    [System.SerializableAttribute()]
    public partial class Produto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EconoFood.ProdutoService.ProdutoDetalhe DetalheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<EconoFood.ProdutoService.ProdutoImagem> ImagensField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoProdutoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EconoFood.ProdutoService.ProdutoDetalhe Detalhe {
            get {
                return this.DetalheField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalheField, value) != true)) {
                    this.DetalheField = value;
                    this.RaisePropertyChanged("Detalhe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProduto {
            get {
                return this.IdProdutoField;
            }
            set {
                if ((this.IdProdutoField.Equals(value) != true)) {
                    this.IdProdutoField = value;
                    this.RaisePropertyChanged("IdProduto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<EconoFood.ProdutoService.ProdutoImagem> Imagens {
            get {
                return this.ImagensField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagensField, value) != true)) {
                    this.ImagensField = value;
                    this.RaisePropertyChanged("Imagens");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoProduto {
            get {
                return this.TipoProdutoField;
            }
            set {
                if ((this.TipoProdutoField.Equals(value) != true)) {
                    this.TipoProdutoField = value;
                    this.RaisePropertyChanged("TipoProduto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProdutoDetalhe", Namespace="http://schemas.datacontract.org/2004/07/EconoFood.Services.DTO")]
    [System.SerializableAttribute()]
    public partial class ProdutoDetalhe : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DimensaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProdutoDetalheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ValorVendaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dimensao {
            get {
                return this.DimensaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DimensaoField, value) != true)) {
                    this.DimensaoField = value;
                    this.RaisePropertyChanged("Dimensao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProduto {
            get {
                return this.IdProdutoField;
            }
            set {
                if ((this.IdProdutoField.Equals(value) != true)) {
                    this.IdProdutoField = value;
                    this.RaisePropertyChanged("IdProduto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProdutoDetalhe {
            get {
                return this.IdProdutoDetalheField;
            }
            set {
                if ((this.IdProdutoDetalheField.Equals(value) != true)) {
                    this.IdProdutoDetalheField = value;
                    this.RaisePropertyChanged("IdProdutoDetalhe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Peso {
            get {
                return this.PesoField;
            }
            set {
                if ((object.ReferenceEquals(this.PesoField, value) != true)) {
                    this.PesoField = value;
                    this.RaisePropertyChanged("Peso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ValorVenda {
            get {
                return this.ValorVendaField;
            }
            set {
                if ((this.ValorVendaField.Equals(value) != true)) {
                    this.ValorVendaField = value;
                    this.RaisePropertyChanged("ValorVenda");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProdutoImagem", Namespace="http://schemas.datacontract.org/2004/07/EconoFood.Services.DTO")]
    [System.SerializableAttribute()]
    public partial class ProdutoImagem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdImagemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImagemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short IdImagem {
            get {
                return this.IdImagemField;
            }
            set {
                if ((this.IdImagemField.Equals(value) != true)) {
                    this.IdImagemField = value;
                    this.RaisePropertyChanged("IdImagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProduto {
            get {
                return this.IdProdutoField;
            }
            set {
                if ((this.IdProdutoField.Equals(value) != true)) {
                    this.IdProdutoField = value;
                    this.RaisePropertyChanged("IdProduto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Imagem {
            get {
                return this.ImagemField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagemField, value) != true)) {
                    this.ImagemField = value;
                    this.RaisePropertyChanged("Imagem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Comparacao", Namespace="http://schemas.datacontract.org/2004/07/EconoFood.Services.DTO")]
    [System.SerializableAttribute()]
    public partial class Comparacao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short PartnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<EconoFood.ProdutoService.Produto> ProdutosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ScoreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Partner {
            get {
                return this.PartnerField;
            }
            set {
                if ((this.PartnerField.Equals(value) != true)) {
                    this.PartnerField = value;
                    this.RaisePropertyChanged("Partner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<EconoFood.ProdutoService.Produto> Produtos {
            get {
                return this.ProdutosField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdutosField, value) != true)) {
                    this.ProdutosField = value;
                    this.RaisePropertyChanged("Produtos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProdutoService.IProduto")]
    public interface IProduto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduto/Listar", ReplyAction="http://tempuri.org/IProduto/ListarResponse")]
        EconoFood.ProdutoService.ListarResponse Listar(EconoFood.ProdutoService.ListarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduto/Listar", ReplyAction="http://tempuri.org/IProduto/ListarResponse")]
        System.Threading.Tasks.Task<EconoFood.ProdutoService.ListarResponse> ListarAsync(EconoFood.ProdutoService.ListarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduto/ListarPorCategoria", ReplyAction="http://tempuri.org/IProduto/ListarPorCategoriaResponse")]
        EconoFood.ProdutoService.ListarPorCategoriaResponse ListarPorCategoria(EconoFood.ProdutoService.ListarPorCategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduto/ListarPorCategoria", ReplyAction="http://tempuri.org/IProduto/ListarPorCategoriaResponse")]
        System.Threading.Tasks.Task<EconoFood.ProdutoService.ListarPorCategoriaResponse> ListarPorCategoriaAsync(EconoFood.ProdutoService.ListarPorCategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduto/PesquisarPorNome", ReplyAction="http://tempuri.org/IProduto/PesquisarPorNomeResponse")]
        EconoFood.ProdutoService.PesquisarPorNomeResponse PesquisarPorNome(EconoFood.ProdutoService.PesquisarPorNomeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduto/PesquisarPorNome", ReplyAction="http://tempuri.org/IProduto/PesquisarPorNomeResponse")]
        System.Threading.Tasks.Task<EconoFood.ProdutoService.PesquisarPorNomeResponse> PesquisarPorNomeAsync(EconoFood.ProdutoService.PesquisarPorNomeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduto/PesquisarPorID", ReplyAction="http://tempuri.org/IProduto/PesquisarPorIDResponse")]
        EconoFood.ProdutoService.PesquisarPorIDResponse PesquisarPorID(EconoFood.ProdutoService.PesquisarPorIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduto/PesquisarPorID", ReplyAction="http://tempuri.org/IProduto/PesquisarPorIDResponse")]
        System.Threading.Tasks.Task<EconoFood.ProdutoService.PesquisarPorIDResponse> PesquisarPorIDAsync(EconoFood.ProdutoService.PesquisarPorIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduto/Gravar", ReplyAction="http://tempuri.org/IProduto/GravarResponse")]
        EconoFood.ProdutoService.GravarResponse Gravar(EconoFood.ProdutoService.GravarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduto/Gravar", ReplyAction="http://tempuri.org/IProduto/GravarResponse")]
        System.Threading.Tasks.Task<EconoFood.ProdutoService.GravarResponse> GravarAsync(EconoFood.ProdutoService.GravarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduto/ListarImagens", ReplyAction="http://tempuri.org/IProduto/ListarImagensResponse")]
        EconoFood.ProdutoService.ListarImagensResponse ListarImagens(EconoFood.ProdutoService.ListarImagensRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduto/ListarImagens", ReplyAction="http://tempuri.org/IProduto/ListarImagensResponse")]
        System.Threading.Tasks.Task<EconoFood.ProdutoService.ListarImagensResponse> ListarImagensAsync(EconoFood.ProdutoService.ListarImagensRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduto/Comparar", ReplyAction="http://tempuri.org/IProduto/CompararResponse")]
        EconoFood.ProdutoService.CompararResponse Comparar(EconoFood.ProdutoService.CompararRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduto/Comparar", ReplyAction="http://tempuri.org/IProduto/CompararResponse")]
        System.Threading.Tasks.Task<EconoFood.ProdutoService.CompararResponse> CompararAsync(EconoFood.ProdutoService.CompararRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Listar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarRequest {
        
        public ListarRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<EconoFood.ProdutoService.Produto> ListarResult;
        
        public ListarResponse() {
        }
        
        public ListarResponse(System.Collections.Generic.List<EconoFood.ProdutoService.Produto> ListarResult) {
            this.ListarResult = ListarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarPorCategoria", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarPorCategoriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int TipoProduto;
        
        public ListarPorCategoriaRequest() {
        }
        
        public ListarPorCategoriaRequest(int TipoProduto) {
            this.TipoProduto = TipoProduto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarPorCategoriaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarPorCategoriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<EconoFood.ProdutoService.Produto> ListarPorCategoriaResult;
        
        public ListarPorCategoriaResponse() {
        }
        
        public ListarPorCategoriaResponse(System.Collections.Generic.List<EconoFood.ProdutoService.Produto> ListarPorCategoriaResult) {
            this.ListarPorCategoriaResult = ListarPorCategoriaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PesquisarPorNome", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PesquisarPorNomeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nomeProduto;
        
        public PesquisarPorNomeRequest() {
        }
        
        public PesquisarPorNomeRequest(string nomeProduto) {
            this.nomeProduto = nomeProduto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PesquisarPorNomeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PesquisarPorNomeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<EconoFood.ProdutoService.Produto> PesquisarPorNomeResult;
        
        public PesquisarPorNomeResponse() {
        }
        
        public PesquisarPorNomeResponse(System.Collections.Generic.List<EconoFood.ProdutoService.Produto> PesquisarPorNomeResult) {
            this.PesquisarPorNomeResult = PesquisarPorNomeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PesquisarPorID", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PesquisarPorIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int idProduto;
        
        public PesquisarPorIDRequest() {
        }
        
        public PesquisarPorIDRequest(int idProduto) {
            this.idProduto = idProduto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PesquisarPorIDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PesquisarPorIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public EconoFood.ProdutoService.Produto PesquisarPorIDResult;
        
        public PesquisarPorIDResponse() {
        }
        
        public PesquisarPorIDResponse(EconoFood.ProdutoService.Produto PesquisarPorIDResult) {
            this.PesquisarPorIDResult = PesquisarPorIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Gravar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GravarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public EconoFood.ProdutoService.Produto produto;
        
        public GravarRequest() {
        }
        
        public GravarRequest(EconoFood.ProdutoService.Produto produto) {
            this.produto = produto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GravarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GravarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int GravarResult;
        
        public GravarResponse() {
        }
        
        public GravarResponse(int GravarResult) {
            this.GravarResult = GravarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarImagens", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarImagensRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int idProduto;
        
        public ListarImagensRequest() {
        }
        
        public ListarImagensRequest(int idProduto) {
            this.idProduto = idProduto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarImagensResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarImagensResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<EconoFood.ProdutoService.ProdutoImagem> ListarImagensResult;
        
        public ListarImagensResponse() {
        }
        
        public ListarImagensResponse(System.Collections.Generic.List<EconoFood.ProdutoService.ProdutoImagem> ListarImagensResult) {
            this.ListarImagensResult = ListarImagensResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Comparar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CompararRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<EconoFood.ProdutoService.Produto> produtos;
        
        public CompararRequest() {
        }
        
        public CompararRequest(System.Collections.Generic.List<EconoFood.ProdutoService.Produto> produtos) {
            this.produtos = produtos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CompararResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CompararResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<EconoFood.ProdutoService.Comparacao> CompararResult;
        
        public CompararResponse() {
        }
        
        public CompararResponse(System.Collections.Generic.List<EconoFood.ProdutoService.Comparacao> CompararResult) {
            this.CompararResult = CompararResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProdutoChannel : EconoFood.ProdutoService.IProduto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProdutoClient : System.ServiceModel.ClientBase<EconoFood.ProdutoService.IProduto>, EconoFood.ProdutoService.IProduto {
        
        public ProdutoClient() {
        }
        
        public ProdutoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProdutoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EconoFood.ProdutoService.ListarResponse Listar(EconoFood.ProdutoService.ListarRequest request) {
            return base.Channel.Listar(request);
        }
        
        public System.Threading.Tasks.Task<EconoFood.ProdutoService.ListarResponse> ListarAsync(EconoFood.ProdutoService.ListarRequest request) {
            return base.Channel.ListarAsync(request);
        }
        
        public EconoFood.ProdutoService.ListarPorCategoriaResponse ListarPorCategoria(EconoFood.ProdutoService.ListarPorCategoriaRequest request) {
            return base.Channel.ListarPorCategoria(request);
        }
        
        public System.Threading.Tasks.Task<EconoFood.ProdutoService.ListarPorCategoriaResponse> ListarPorCategoriaAsync(EconoFood.ProdutoService.ListarPorCategoriaRequest request) {
            return base.Channel.ListarPorCategoriaAsync(request);
        }
        
        public EconoFood.ProdutoService.PesquisarPorNomeResponse PesquisarPorNome(EconoFood.ProdutoService.PesquisarPorNomeRequest request) {
            return base.Channel.PesquisarPorNome(request);
        }
        
        public System.Threading.Tasks.Task<EconoFood.ProdutoService.PesquisarPorNomeResponse> PesquisarPorNomeAsync(EconoFood.ProdutoService.PesquisarPorNomeRequest request) {
            return base.Channel.PesquisarPorNomeAsync(request);
        }
        
        public EconoFood.ProdutoService.PesquisarPorIDResponse PesquisarPorID(EconoFood.ProdutoService.PesquisarPorIDRequest request) {
            return base.Channel.PesquisarPorID(request);
        }
        
        public System.Threading.Tasks.Task<EconoFood.ProdutoService.PesquisarPorIDResponse> PesquisarPorIDAsync(EconoFood.ProdutoService.PesquisarPorIDRequest request) {
            return base.Channel.PesquisarPorIDAsync(request);
        }
        
        public EconoFood.ProdutoService.GravarResponse Gravar(EconoFood.ProdutoService.GravarRequest request) {
            return base.Channel.Gravar(request);
        }
        
        public System.Threading.Tasks.Task<EconoFood.ProdutoService.GravarResponse> GravarAsync(EconoFood.ProdutoService.GravarRequest request) {
            return base.Channel.GravarAsync(request);
        }
        
        public EconoFood.ProdutoService.ListarImagensResponse ListarImagens(EconoFood.ProdutoService.ListarImagensRequest request) {
            return base.Channel.ListarImagens(request);
        }
        
        public System.Threading.Tasks.Task<EconoFood.ProdutoService.ListarImagensResponse> ListarImagensAsync(EconoFood.ProdutoService.ListarImagensRequest request) {
            return base.Channel.ListarImagensAsync(request);
        }
        
        public EconoFood.ProdutoService.CompararResponse Comparar(EconoFood.ProdutoService.CompararRequest request) {
            return base.Channel.Comparar(request);
        }
        
        public System.Threading.Tasks.Task<EconoFood.ProdutoService.CompararResponse> CompararAsync(EconoFood.ProdutoService.CompararRequest request) {
            return base.Channel.CompararAsync(request);
        }
    }
}
