//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EconoFood.Admin.UsuarioService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/EconoFood.Services.DTO")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataCadastroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataNascimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short PerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenhaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CPF {
            get {
                return this.CPFField;
            }
            set {
                if ((object.ReferenceEquals(this.CPFField, value) != true)) {
                    this.CPFField = value;
                    this.RaisePropertyChanged("CPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataCadastro {
            get {
                return this.DataCadastroField;
            }
            set {
                if ((this.DataCadastroField.Equals(value) != true)) {
                    this.DataCadastroField = value;
                    this.RaisePropertyChanged("DataCadastro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataNascimento {
            get {
                return this.DataNascimentoField;
            }
            set {
                if ((this.DataNascimentoField.Equals(value) != true)) {
                    this.DataNascimentoField = value;
                    this.RaisePropertyChanged("DataNascimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Perfil {
            get {
                return this.PerfilField;
            }
            set {
                if ((this.PerfilField.Equals(value) != true)) {
                    this.PerfilField = value;
                    this.RaisePropertyChanged("Perfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Senha {
            get {
                return this.SenhaField;
            }
            set {
                if ((object.ReferenceEquals(this.SenhaField, value) != true)) {
                    this.SenhaField = value;
                    this.RaisePropertyChanged("Senha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UsuarioService.IUsuario")]
    public interface IUsuario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/Listar", ReplyAction="http://tempuri.org/IUsuario/ListarResponse")]
        System.Collections.Generic.List<EconoFood.Admin.UsuarioService.Usuario> Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/Listar", ReplyAction="http://tempuri.org/IUsuario/ListarResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<EconoFood.Admin.UsuarioService.Usuario>> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/ListarPorStatus", ReplyAction="http://tempuri.org/IUsuario/ListarPorStatusResponse")]
        System.Collections.Generic.List<EconoFood.Admin.UsuarioService.Usuario> ListarPorStatus(bool retornarInativos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/ListarPorStatus", ReplyAction="http://tempuri.org/IUsuario/ListarPorStatusResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<EconoFood.Admin.UsuarioService.Usuario>> ListarPorStatusAsync(bool retornarInativos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/PesquisarPorID", ReplyAction="http://tempuri.org/IUsuario/PesquisarPorIDResponse")]
        EconoFood.Admin.UsuarioService.Usuario PesquisarPorID(short idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/PesquisarPorID", ReplyAction="http://tempuri.org/IUsuario/PesquisarPorIDResponse")]
        System.Threading.Tasks.Task<EconoFood.Admin.UsuarioService.Usuario> PesquisarPorIDAsync(short idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/Gravar", ReplyAction="http://tempuri.org/IUsuario/GravarResponse")]
        int Gravar(EconoFood.Admin.UsuarioService.Usuario Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/Gravar", ReplyAction="http://tempuri.org/IUsuario/GravarResponse")]
        System.Threading.Tasks.Task<int> GravarAsync(EconoFood.Admin.UsuarioService.Usuario Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/Excluir", ReplyAction="http://tempuri.org/IUsuario/ExcluirResponse")]
        void Excluir(EconoFood.Admin.UsuarioService.Usuario Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/Excluir", ReplyAction="http://tempuri.org/IUsuario/ExcluirResponse")]
        System.Threading.Tasks.Task ExcluirAsync(EconoFood.Admin.UsuarioService.Usuario Usuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuarioChannel : EconoFood.Admin.UsuarioService.IUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioClient : System.ServiceModel.ClientBase<EconoFood.Admin.UsuarioService.IUsuario>, EconoFood.Admin.UsuarioService.IUsuario {
        
        public UsuarioClient() {
        }
        
        public UsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<EconoFood.Admin.UsuarioService.Usuario> Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<EconoFood.Admin.UsuarioService.Usuario>> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public System.Collections.Generic.List<EconoFood.Admin.UsuarioService.Usuario> ListarPorStatus(bool retornarInativos) {
            return base.Channel.ListarPorStatus(retornarInativos);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<EconoFood.Admin.UsuarioService.Usuario>> ListarPorStatusAsync(bool retornarInativos) {
            return base.Channel.ListarPorStatusAsync(retornarInativos);
        }
        
        public EconoFood.Admin.UsuarioService.Usuario PesquisarPorID(short idUsuario) {
            return base.Channel.PesquisarPorID(idUsuario);
        }
        
        public System.Threading.Tasks.Task<EconoFood.Admin.UsuarioService.Usuario> PesquisarPorIDAsync(short idUsuario) {
            return base.Channel.PesquisarPorIDAsync(idUsuario);
        }
        
        public int Gravar(EconoFood.Admin.UsuarioService.Usuario Usuario) {
            return base.Channel.Gravar(Usuario);
        }
        
        public System.Threading.Tasks.Task<int> GravarAsync(EconoFood.Admin.UsuarioService.Usuario Usuario) {
            return base.Channel.GravarAsync(Usuario);
        }
        
        public void Excluir(EconoFood.Admin.UsuarioService.Usuario Usuario) {
            base.Channel.Excluir(Usuario);
        }
        
        public System.Threading.Tasks.Task ExcluirAsync(EconoFood.Admin.UsuarioService.Usuario Usuario) {
            return base.Channel.ExcluirAsync(Usuario);
        }
    }
}
