//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EconoFood.Services.DataAccess.SondaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProdutoSonda", Namespace="http://schemas.datacontract.org/2004/07/ServicoSondaHipermercados")]
    [System.SerializableAttribute()]
    public partial class ProdutoSonda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProdutoSondaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeProdutoSondaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecoProdutoSondaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProdutoSonda {
            get {
                return this.IdProdutoSondaField;
            }
            set {
                if ((this.IdProdutoSondaField.Equals(value) != true)) {
                    this.IdProdutoSondaField = value;
                    this.RaisePropertyChanged("IdProdutoSonda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeProdutoSonda {
            get {
                return this.NomeProdutoSondaField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeProdutoSondaField, value) != true)) {
                    this.NomeProdutoSondaField = value;
                    this.RaisePropertyChanged("NomeProdutoSonda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PrecoProdutoSonda {
            get {
                return this.PrecoProdutoSondaField;
            }
            set {
                if ((this.PrecoProdutoSondaField.Equals(value) != true)) {
                    this.PrecoProdutoSondaField = value;
                    this.RaisePropertyChanged("PrecoProdutoSonda");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SondaService.IServiceSonda")]
    public interface IServiceSonda {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSonda/ObterPrecoProdutoSonda", ReplyAction="http://tempuri.org/IServiceSonda/ObterPrecoProdutoSondaResponse")]
        EconoFood.Services.DataAccess.SondaService.ObterPrecoProdutoSondaResponse ObterPrecoProdutoSonda(EconoFood.Services.DataAccess.SondaService.ObterPrecoProdutoSondaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSonda/ObterPrecoProdutoSonda", ReplyAction="http://tempuri.org/IServiceSonda/ObterPrecoProdutoSondaResponse")]
        System.Threading.Tasks.Task<EconoFood.Services.DataAccess.SondaService.ObterPrecoProdutoSondaResponse> ObterPrecoProdutoSondaAsync(EconoFood.Services.DataAccess.SondaService.ObterPrecoProdutoSondaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObterPrecoProdutoSonda", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObterPrecoProdutoSondaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nomeProduto;
        
        public ObterPrecoProdutoSondaRequest() {
        }
        
        public ObterPrecoProdutoSondaRequest(string nomeProduto) {
            this.nomeProduto = nomeProduto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObterPrecoProdutoSondaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObterPrecoProdutoSondaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<EconoFood.Services.DataAccess.SondaService.ProdutoSonda> ObterPrecoProdutoSondaResult;
        
        public ObterPrecoProdutoSondaResponse() {
        }
        
        public ObterPrecoProdutoSondaResponse(System.Collections.Generic.List<EconoFood.Services.DataAccess.SondaService.ProdutoSonda> ObterPrecoProdutoSondaResult) {
            this.ObterPrecoProdutoSondaResult = ObterPrecoProdutoSondaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceSondaChannel : EconoFood.Services.DataAccess.SondaService.IServiceSonda, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSondaClient : System.ServiceModel.ClientBase<EconoFood.Services.DataAccess.SondaService.IServiceSonda>, EconoFood.Services.DataAccess.SondaService.IServiceSonda {
        
        public ServiceSondaClient() {
        }
        
        public ServiceSondaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSondaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSondaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSondaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EconoFood.Services.DataAccess.SondaService.ObterPrecoProdutoSondaResponse ObterPrecoProdutoSonda(EconoFood.Services.DataAccess.SondaService.ObterPrecoProdutoSondaRequest request) {
            return base.Channel.ObterPrecoProdutoSonda(request);
        }
        
        public System.Threading.Tasks.Task<EconoFood.Services.DataAccess.SondaService.ObterPrecoProdutoSondaResponse> ObterPrecoProdutoSondaAsync(EconoFood.Services.DataAccess.SondaService.ObterPrecoProdutoSondaRequest request) {
            return base.Channel.ObterPrecoProdutoSondaAsync(request);
        }
    }
}
