//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EconoFood.Services.DataAccess.SondaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SondaService.IServiceSonda")]
    public interface IServiceSonda {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSonda/ObterPrecoProdutoSonda", ReplyAction="http://tempuri.org/IServiceSonda/ObterPrecoProdutoSondaResponse")]
        EconoFood.Services.DataAccess.SondaService.ObterPrecoProdutoSondaResponse ObterPrecoProdutoSonda(EconoFood.Services.DataAccess.SondaService.ObterPrecoProdutoSondaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSonda/ObterPrecoProdutoSonda", ReplyAction="http://tempuri.org/IServiceSonda/ObterPrecoProdutoSondaResponse")]
        System.Threading.Tasks.Task<EconoFood.Services.DataAccess.SondaService.ObterPrecoProdutoSondaResponse> ObterPrecoProdutoSondaAsync(EconoFood.Services.DataAccess.SondaService.ObterPrecoProdutoSondaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObterPrecoProdutoSonda", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObterPrecoProdutoSondaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int idProduto;
        
        public ObterPrecoProdutoSondaRequest() {
        }
        
        public ObterPrecoProdutoSondaRequest(int idProduto) {
            this.idProduto = idProduto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObterPrecoProdutoSondaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObterPrecoProdutoSondaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Nullable<decimal> ObterPrecoProdutoSondaResult;
        
        public ObterPrecoProdutoSondaResponse() {
        }
        
        public ObterPrecoProdutoSondaResponse(System.Nullable<decimal> ObterPrecoProdutoSondaResult) {
            this.ObterPrecoProdutoSondaResult = ObterPrecoProdutoSondaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceSondaChannel : EconoFood.Services.DataAccess.SondaService.IServiceSonda, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSondaClient : System.ServiceModel.ClientBase<EconoFood.Services.DataAccess.SondaService.IServiceSonda>, EconoFood.Services.DataAccess.SondaService.IServiceSonda {
        
        public ServiceSondaClient() {
        }
        
        public ServiceSondaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSondaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSondaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSondaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EconoFood.Services.DataAccess.SondaService.ObterPrecoProdutoSondaResponse ObterPrecoProdutoSonda(EconoFood.Services.DataAccess.SondaService.ObterPrecoProdutoSondaRequest request) {
            return base.Channel.ObterPrecoProdutoSonda(request);
        }
        
        public System.Threading.Tasks.Task<EconoFood.Services.DataAccess.SondaService.ObterPrecoProdutoSondaResponse> ObterPrecoProdutoSondaAsync(EconoFood.Services.DataAccess.SondaService.ObterPrecoProdutoSondaRequest request) {
            return base.Channel.ObterPrecoProdutoSondaAsync(request);
        }
    }
}
