//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EconoFood.Services.DataAccess.ExtraService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProdutoExtra", Namespace="http://schemas.datacontract.org/2004/07/ServicoExtraHipermercados")]
    [System.SerializableAttribute()]
    public partial class ProdutoExtra : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProdutoExtraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeProdutoExtraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecoProdutoExtraField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProdutoExtra {
            get {
                return this.IdProdutoExtraField;
            }
            set {
                if ((this.IdProdutoExtraField.Equals(value) != true)) {
                    this.IdProdutoExtraField = value;
                    this.RaisePropertyChanged("IdProdutoExtra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeProdutoExtra {
            get {
                return this.NomeProdutoExtraField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeProdutoExtraField, value) != true)) {
                    this.NomeProdutoExtraField = value;
                    this.RaisePropertyChanged("NomeProdutoExtra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PrecoProdutoExtra {
            get {
                return this.PrecoProdutoExtraField;
            }
            set {
                if ((this.PrecoProdutoExtraField.Equals(value) != true)) {
                    this.PrecoProdutoExtraField = value;
                    this.RaisePropertyChanged("PrecoProdutoExtra");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExtraService.IServiceExtra")]
    public interface IServiceExtra {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceExtra/ObterPrecoProdutoExtra", ReplyAction="http://tempuri.org/IServiceExtra/ObterPrecoProdutoExtraResponse")]
        EconoFood.Services.DataAccess.ExtraService.ObterPrecoProdutoExtraResponse ObterPrecoProdutoExtra(EconoFood.Services.DataAccess.ExtraService.ObterPrecoProdutoExtraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceExtra/ObterPrecoProdutoExtra", ReplyAction="http://tempuri.org/IServiceExtra/ObterPrecoProdutoExtraResponse")]
        System.Threading.Tasks.Task<EconoFood.Services.DataAccess.ExtraService.ObterPrecoProdutoExtraResponse> ObterPrecoProdutoExtraAsync(EconoFood.Services.DataAccess.ExtraService.ObterPrecoProdutoExtraRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObterPrecoProdutoExtra", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObterPrecoProdutoExtraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nomeProduto;
        
        public ObterPrecoProdutoExtraRequest() {
        }
        
        public ObterPrecoProdutoExtraRequest(string nomeProduto) {
            this.nomeProduto = nomeProduto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObterPrecoProdutoExtraResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObterPrecoProdutoExtraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<EconoFood.Services.DataAccess.ExtraService.ProdutoExtra> ObterPrecoProdutoExtraResult;
        
        public ObterPrecoProdutoExtraResponse() {
        }
        
        public ObterPrecoProdutoExtraResponse(System.Collections.Generic.List<EconoFood.Services.DataAccess.ExtraService.ProdutoExtra> ObterPrecoProdutoExtraResult) {
            this.ObterPrecoProdutoExtraResult = ObterPrecoProdutoExtraResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceExtraChannel : EconoFood.Services.DataAccess.ExtraService.IServiceExtra, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceExtraClient : System.ServiceModel.ClientBase<EconoFood.Services.DataAccess.ExtraService.IServiceExtra>, EconoFood.Services.DataAccess.ExtraService.IServiceExtra {
        
        public ServiceExtraClient() {
        }
        
        public ServiceExtraClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceExtraClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceExtraClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceExtraClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EconoFood.Services.DataAccess.ExtraService.ObterPrecoProdutoExtraResponse ObterPrecoProdutoExtra(EconoFood.Services.DataAccess.ExtraService.ObterPrecoProdutoExtraRequest request) {
            return base.Channel.ObterPrecoProdutoExtra(request);
        }
        
        public System.Threading.Tasks.Task<EconoFood.Services.DataAccess.ExtraService.ObterPrecoProdutoExtraResponse> ObterPrecoProdutoExtraAsync(EconoFood.Services.DataAccess.ExtraService.ObterPrecoProdutoExtraRequest request) {
            return base.Channel.ObterPrecoProdutoExtraAsync(request);
        }
    }
}
