//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EconoFood.Services.DataAccess.ExtraService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExtraService.IServiceExtra")]
    public interface IServiceExtra {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceExtra/ObterPrecoProdutoExtra", ReplyAction="http://tempuri.org/IServiceExtra/ObterPrecoProdutoExtraResponse")]
        EconoFood.Services.DataAccess.ExtraService.ObterPrecoProdutoExtraResponse ObterPrecoProdutoExtra(EconoFood.Services.DataAccess.ExtraService.ObterPrecoProdutoExtraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceExtra/ObterPrecoProdutoExtra", ReplyAction="http://tempuri.org/IServiceExtra/ObterPrecoProdutoExtraResponse")]
        System.Threading.Tasks.Task<EconoFood.Services.DataAccess.ExtraService.ObterPrecoProdutoExtraResponse> ObterPrecoProdutoExtraAsync(EconoFood.Services.DataAccess.ExtraService.ObterPrecoProdutoExtraRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObterPrecoProdutoExtra", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObterPrecoProdutoExtraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int idProduto;
        
        public ObterPrecoProdutoExtraRequest() {
        }
        
        public ObterPrecoProdutoExtraRequest(int idProduto) {
            this.idProduto = idProduto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObterPrecoProdutoExtraResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObterPrecoProdutoExtraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Nullable<decimal> ObterPrecoProdutoExtraResult;
        
        public ObterPrecoProdutoExtraResponse() {
        }
        
        public ObterPrecoProdutoExtraResponse(System.Nullable<decimal> ObterPrecoProdutoExtraResult) {
            this.ObterPrecoProdutoExtraResult = ObterPrecoProdutoExtraResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceExtraChannel : EconoFood.Services.DataAccess.ExtraService.IServiceExtra, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceExtraClient : System.ServiceModel.ClientBase<EconoFood.Services.DataAccess.ExtraService.IServiceExtra>, EconoFood.Services.DataAccess.ExtraService.IServiceExtra {
        
        public ServiceExtraClient() {
        }
        
        public ServiceExtraClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceExtraClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceExtraClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceExtraClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EconoFood.Services.DataAccess.ExtraService.ObterPrecoProdutoExtraResponse ObterPrecoProdutoExtra(EconoFood.Services.DataAccess.ExtraService.ObterPrecoProdutoExtraRequest request) {
            return base.Channel.ObterPrecoProdutoExtra(request);
        }
        
        public System.Threading.Tasks.Task<EconoFood.Services.DataAccess.ExtraService.ObterPrecoProdutoExtraResponse> ObterPrecoProdutoExtraAsync(EconoFood.Services.DataAccess.ExtraService.ObterPrecoProdutoExtraRequest request) {
            return base.Channel.ObterPrecoProdutoExtraAsync(request);
        }
    }
}
