//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EconoFood.Admin.ProdutoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produto", Namespace="http://schemas.datacontract.org/2004/07/EconoFood.Services.DTO")]
    [System.SerializableAttribute()]
    public partial class Produto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<EconoFood.Admin.ProdutoService.ProdutoImagem> ImagensField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProduto {
            get {
                return this.IdProdutoField;
            }
            set {
                if ((this.IdProdutoField.Equals(value) != true)) {
                    this.IdProdutoField = value;
                    this.RaisePropertyChanged("IdProduto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<EconoFood.Admin.ProdutoService.ProdutoImagem> Imagens {
            get {
                return this.ImagensField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagensField, value) != true)) {
                    this.ImagensField = value;
                    this.RaisePropertyChanged("Imagens");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProdutoImagem", Namespace="http://schemas.datacontract.org/2004/07/EconoFood.Services.DTO")]
    [System.SerializableAttribute()]
    public partial class ProdutoImagem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdImagemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImagemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short IdImagem {
            get {
                return this.IdImagemField;
            }
            set {
                if ((this.IdImagemField.Equals(value) != true)) {
                    this.IdImagemField = value;
                    this.RaisePropertyChanged("IdImagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProduto {
            get {
                return this.IdProdutoField;
            }
            set {
                if ((this.IdProdutoField.Equals(value) != true)) {
                    this.IdProdutoField = value;
                    this.RaisePropertyChanged("IdProduto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Imagem {
            get {
                return this.ImagemField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagemField, value) != true)) {
                    this.ImagemField = value;
                    this.RaisePropertyChanged("Imagem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProdutoService.IProduto")]
    public interface IProduto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduto/Listar", ReplyAction="http://tempuri.org/IProduto/ListarResponse")]
        EconoFood.Admin.ProdutoService.ListarResponse Listar(EconoFood.Admin.ProdutoService.ListarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduto/Listar", ReplyAction="http://tempuri.org/IProduto/ListarResponse")]
        System.Threading.Tasks.Task<EconoFood.Admin.ProdutoService.ListarResponse> ListarAsync(EconoFood.Admin.ProdutoService.ListarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduto/PesquisarPorNome", ReplyAction="http://tempuri.org/IProduto/PesquisarPorNomeResponse")]
        EconoFood.Admin.ProdutoService.PesquisarPorNomeResponse PesquisarPorNome(EconoFood.Admin.ProdutoService.PesquisarPorNomeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduto/PesquisarPorNome", ReplyAction="http://tempuri.org/IProduto/PesquisarPorNomeResponse")]
        System.Threading.Tasks.Task<EconoFood.Admin.ProdutoService.PesquisarPorNomeResponse> PesquisarPorNomeAsync(EconoFood.Admin.ProdutoService.PesquisarPorNomeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduto/PesquisarPorID", ReplyAction="http://tempuri.org/IProduto/PesquisarPorIDResponse")]
        EconoFood.Admin.ProdutoService.PesquisarPorIDResponse PesquisarPorID(EconoFood.Admin.ProdutoService.PesquisarPorIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduto/PesquisarPorID", ReplyAction="http://tempuri.org/IProduto/PesquisarPorIDResponse")]
        System.Threading.Tasks.Task<EconoFood.Admin.ProdutoService.PesquisarPorIDResponse> PesquisarPorIDAsync(EconoFood.Admin.ProdutoService.PesquisarPorIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduto/Gravar", ReplyAction="http://tempuri.org/IProduto/GravarResponse")]
        EconoFood.Admin.ProdutoService.GravarResponse Gravar(EconoFood.Admin.ProdutoService.GravarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduto/Gravar", ReplyAction="http://tempuri.org/IProduto/GravarResponse")]
        System.Threading.Tasks.Task<EconoFood.Admin.ProdutoService.GravarResponse> GravarAsync(EconoFood.Admin.ProdutoService.GravarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduto/ListarImagens", ReplyAction="http://tempuri.org/IProduto/ListarImagensResponse")]
        EconoFood.Admin.ProdutoService.ListarImagensResponse ListarImagens(EconoFood.Admin.ProdutoService.ListarImagensRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduto/ListarImagens", ReplyAction="http://tempuri.org/IProduto/ListarImagensResponse")]
        System.Threading.Tasks.Task<EconoFood.Admin.ProdutoService.ListarImagensResponse> ListarImagensAsync(EconoFood.Admin.ProdutoService.ListarImagensRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Listar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarRequest {
        
        public ListarRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<EconoFood.Admin.ProdutoService.Produto> ListarResult;
        
        public ListarResponse() {
        }
        
        public ListarResponse(System.Collections.Generic.List<EconoFood.Admin.ProdutoService.Produto> ListarResult) {
            this.ListarResult = ListarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PesquisarPorNome", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PesquisarPorNomeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nomeProduto;
        
        public PesquisarPorNomeRequest() {
        }
        
        public PesquisarPorNomeRequest(string nomeProduto) {
            this.nomeProduto = nomeProduto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PesquisarPorNomeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PesquisarPorNomeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<EconoFood.Admin.ProdutoService.Produto> PesquisarPorNomeResult;
        
        public PesquisarPorNomeResponse() {
        }
        
        public PesquisarPorNomeResponse(System.Collections.Generic.List<EconoFood.Admin.ProdutoService.Produto> PesquisarPorNomeResult) {
            this.PesquisarPorNomeResult = PesquisarPorNomeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PesquisarPorID", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PesquisarPorIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int idProduto;
        
        public PesquisarPorIDRequest() {
        }
        
        public PesquisarPorIDRequest(int idProduto) {
            this.idProduto = idProduto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PesquisarPorIDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PesquisarPorIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public EconoFood.Admin.ProdutoService.Produto PesquisarPorIDResult;
        
        public PesquisarPorIDResponse() {
        }
        
        public PesquisarPorIDResponse(EconoFood.Admin.ProdutoService.Produto PesquisarPorIDResult) {
            this.PesquisarPorIDResult = PesquisarPorIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Gravar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GravarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public EconoFood.Admin.ProdutoService.Produto produto;
        
        public GravarRequest() {
        }
        
        public GravarRequest(EconoFood.Admin.ProdutoService.Produto produto) {
            this.produto = produto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GravarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GravarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int GravarResult;
        
        public GravarResponse() {
        }
        
        public GravarResponse(int GravarResult) {
            this.GravarResult = GravarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarImagens", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarImagensRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int idProduto;
        
        public ListarImagensRequest() {
        }
        
        public ListarImagensRequest(int idProduto) {
            this.idProduto = idProduto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarImagensResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarImagensResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<EconoFood.Admin.ProdutoService.ProdutoImagem> ListarImagensResult;
        
        public ListarImagensResponse() {
        }
        
        public ListarImagensResponse(System.Collections.Generic.List<EconoFood.Admin.ProdutoService.ProdutoImagem> ListarImagensResult) {
            this.ListarImagensResult = ListarImagensResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProdutoChannel : EconoFood.Admin.ProdutoService.IProduto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProdutoClient : System.ServiceModel.ClientBase<EconoFood.Admin.ProdutoService.IProduto>, EconoFood.Admin.ProdutoService.IProduto {
        
        public ProdutoClient() {
        }
        
        public ProdutoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProdutoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EconoFood.Admin.ProdutoService.ListarResponse Listar(EconoFood.Admin.ProdutoService.ListarRequest request) {
            return base.Channel.Listar(request);
        }
        
        public System.Threading.Tasks.Task<EconoFood.Admin.ProdutoService.ListarResponse> ListarAsync(EconoFood.Admin.ProdutoService.ListarRequest request) {
            return base.Channel.ListarAsync(request);
        }
        
        public EconoFood.Admin.ProdutoService.PesquisarPorNomeResponse PesquisarPorNome(EconoFood.Admin.ProdutoService.PesquisarPorNomeRequest request) {
            return base.Channel.PesquisarPorNome(request);
        }
        
        public System.Threading.Tasks.Task<EconoFood.Admin.ProdutoService.PesquisarPorNomeResponse> PesquisarPorNomeAsync(EconoFood.Admin.ProdutoService.PesquisarPorNomeRequest request) {
            return base.Channel.PesquisarPorNomeAsync(request);
        }
        
        public EconoFood.Admin.ProdutoService.PesquisarPorIDResponse PesquisarPorID(EconoFood.Admin.ProdutoService.PesquisarPorIDRequest request) {
            return base.Channel.PesquisarPorID(request);
        }
        
        public System.Threading.Tasks.Task<EconoFood.Admin.ProdutoService.PesquisarPorIDResponse> PesquisarPorIDAsync(EconoFood.Admin.ProdutoService.PesquisarPorIDRequest request) {
            return base.Channel.PesquisarPorIDAsync(request);
        }
        
        public EconoFood.Admin.ProdutoService.GravarResponse Gravar(EconoFood.Admin.ProdutoService.GravarRequest request) {
            return base.Channel.Gravar(request);
        }
        
        public System.Threading.Tasks.Task<EconoFood.Admin.ProdutoService.GravarResponse> GravarAsync(EconoFood.Admin.ProdutoService.GravarRequest request) {
            return base.Channel.GravarAsync(request);
        }
        
        public EconoFood.Admin.ProdutoService.ListarImagensResponse ListarImagens(EconoFood.Admin.ProdutoService.ListarImagensRequest request) {
            return base.Channel.ListarImagens(request);
        }
        
        public System.Threading.Tasks.Task<EconoFood.Admin.ProdutoService.ListarImagensResponse> ListarImagensAsync(EconoFood.Admin.ProdutoService.ListarImagensRequest request) {
            return base.Channel.ListarImagensAsync(request);
        }
    }
}
