//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EconoFood.Services.DataAccess.PaoDeAcucarService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PaoDeAcucarService.IServicePaoDeAcucar")]
    public interface IServicePaoDeAcucar {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePaoDeAcucar/ObterPrecoProdutoPaoDeAcucar", ReplyAction="http://tempuri.org/IServicePaoDeAcucar/ObterPrecoProdutoPaoDeAcucarResponse")]
        EconoFood.Services.DataAccess.PaoDeAcucarService.ObterPrecoProdutoPaoDeAcucarResponse ObterPrecoProdutoPaoDeAcucar(EconoFood.Services.DataAccess.PaoDeAcucarService.ObterPrecoProdutoPaoDeAcucarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePaoDeAcucar/ObterPrecoProdutoPaoDeAcucar", ReplyAction="http://tempuri.org/IServicePaoDeAcucar/ObterPrecoProdutoPaoDeAcucarResponse")]
        System.Threading.Tasks.Task<EconoFood.Services.DataAccess.PaoDeAcucarService.ObterPrecoProdutoPaoDeAcucarResponse> ObterPrecoProdutoPaoDeAcucarAsync(EconoFood.Services.DataAccess.PaoDeAcucarService.ObterPrecoProdutoPaoDeAcucarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObterPrecoProdutoPaoDeAcucar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObterPrecoProdutoPaoDeAcucarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int idProduto;
        
        public ObterPrecoProdutoPaoDeAcucarRequest() {
        }
        
        public ObterPrecoProdutoPaoDeAcucarRequest(int idProduto) {
            this.idProduto = idProduto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObterPrecoProdutoPaoDeAcucarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ObterPrecoProdutoPaoDeAcucarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Nullable<decimal> ObterPrecoProdutoPaoDeAcucarResult;
        
        public ObterPrecoProdutoPaoDeAcucarResponse() {
        }
        
        public ObterPrecoProdutoPaoDeAcucarResponse(System.Nullable<decimal> ObterPrecoProdutoPaoDeAcucarResult) {
            this.ObterPrecoProdutoPaoDeAcucarResult = ObterPrecoProdutoPaoDeAcucarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicePaoDeAcucarChannel : EconoFood.Services.DataAccess.PaoDeAcucarService.IServicePaoDeAcucar, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicePaoDeAcucarClient : System.ServiceModel.ClientBase<EconoFood.Services.DataAccess.PaoDeAcucarService.IServicePaoDeAcucar>, EconoFood.Services.DataAccess.PaoDeAcucarService.IServicePaoDeAcucar {
        
        public ServicePaoDeAcucarClient() {
        }
        
        public ServicePaoDeAcucarClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicePaoDeAcucarClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePaoDeAcucarClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePaoDeAcucarClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EconoFood.Services.DataAccess.PaoDeAcucarService.ObterPrecoProdutoPaoDeAcucarResponse ObterPrecoProdutoPaoDeAcucar(EconoFood.Services.DataAccess.PaoDeAcucarService.ObterPrecoProdutoPaoDeAcucarRequest request) {
            return base.Channel.ObterPrecoProdutoPaoDeAcucar(request);
        }
        
        public System.Threading.Tasks.Task<EconoFood.Services.DataAccess.PaoDeAcucarService.ObterPrecoProdutoPaoDeAcucarResponse> ObterPrecoProdutoPaoDeAcucarAsync(EconoFood.Services.DataAccess.PaoDeAcucarService.ObterPrecoProdutoPaoDeAcucarRequest request) {
            return base.Channel.ObterPrecoProdutoPaoDeAcucarAsync(request);
        }
    }
}
